### PR TITLE
Fix for misaligned Classic SEO icon

### PR DESCRIPTION
**Pull request by timbocode**
Resolves the misaligned icon in the top admin bar and side menu.

image

### CODE REVIEW

**Comment by nylen** [comment]
Confirmed, this fixes the icon misalignment and also improves the colors a bit.

There is still one minor color issue, when hovering the icon in the menu it doesn't turn blue:

2020-07-25T21-29-07Z

If you want to be able to style the internal elements of a SVG image then the SVG content has to be inline instead of referenced via ``, I think that is the reason this icon isn't turning blue on hover.

I'm not sure how hard it would be to get the SVG content to embed inline in that part of the menu, but it would be good to look for a standardized solution to this problem.

**Comment by timbocode** [comment]
Seems OK to me but could you confirm please James. 

image

**Comment by nylen** [comment]
Tested again and looks good :+1:

**Comment by timbocode** [comment]
Thanks James.

**Pull request merged**
